# Generated by Django 2.2.15 on 2022-01-25 10:21

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220121_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='icons/default.png', max_length=255, null=True, upload_to=account.models.get_profile_image_filepath),
        ),
    ]
